from os import name
import discord
from discord.ext import commands
bot = discord.Client()
bot = commands.Bot(command_prefix='~')


class about(commands.Cog):
 def __init__(self, bot):
  self.bot=bot
 
 @commands.command(name='balls')
 async def genhelp(self,ctx):
  genhel = discord.Embed(title='The help for help pages',color=0xF83252,description='**Main:** Help page for the main commands\n\n**Musichelp:** Help page for the music commands')
  genhel.set_thumbnail(url='https://cdn.discordapp.com/avatars/842927617291321369/5a8d5edc210c292aacf81ec03a9f2ad6.webp?size=4096')
  await ctx.send(embed=genhel)


 @commands.command(name='Musichelp')
 async def MusicHelp(self,ctx):
  mus = discord.Embed(title='Music Commands',color=0xF83252,description='**play:** Plays a selected song from youtube\n\n**queue:** Shows the current song queue\n\n**skip:** Skips the currently playing song\n\n**leave:** Makes the bot leave the voice channel')
  mus.set_thumbnail(url='https://images-na.ssl-images-amazon.com/images/I/61qeoJiZqkL._AC_SL1500_.jpg')
  await ctx.send(embed=mus)
  
 
 @commands.command(name='Main')
 async def Main(self,ctx):
  gen = discord.Embed(title='Most of the commands',color=0xF83252)
  gen.set_thumbnail(url='https://thumbs.dreamstime.com/b/d-white-man-red-questionmark-computer-generated-image-isolated-68105896.jpg')
  gen.add_field(name='Ampquotes',value='Big fag',inline=True)
  gen.add_field(name='BatcockssidePieces',value='His hoes',inline=True)
  gen.add_field(name='BatcocksVirginity',value='...',inline=True)
  gen.add_field(name='BestGameEver',value='Down Bad',inline=True)
  gen.add_field(name='BigAnimeTiddies',value='UwU',inline=True)
  gen.add_field(name='BigTiddiesAndTrauma',value='Onichaaaaan',inline=True)
  gen.add_field(name='BlacktrickAddress',value='Make like dababy and pull up',inline=True)
  gen.add_field(name='Blacktrickquotes',value='coom',inline=True)
  gen.add_field(name='Blacktrickquotes2',value='QuotesV2',inline=True)
  gen.add_field(name='Blacktrickquotes3',value='QuotesV3',inline=True)
  gen.add_field(name='BlacktrickTwitch',value='Kinda shit ngl (jk dont hurt me)',inline=True)
  gen.add_field(name='Blacktrickdadreveal',value='ouch just ouch',inline=True)
  gen.add_field(name='CrispQuotes',value='Crispy as fuck',inline=True)
  gen.add_field(name='CrispsVirginity',value='Not fo long',inline=True)
  gen.add_field(name='DoinYaMom',value='Doin ya mom',inline=True)
  gen.add_field(name='GavinPussy',value='The most pussy',inline=True)
  gen.add_field(name='GodQuotes',value='The quotes of our GOD',inline=True)
  gen.add_field(name='GodQuotes2',value='The quotes of our GOD V2',inline=True)
  gen.add_field(name='JosieQuotesR',value='racism',inline=True)
  gen.add_field(name='JosiesVirginity',value='owo',inline=True)
  gen.add_field(name='LightningMcqueen',value='KACHOW',inline=True)
  gen.add_field(name='Loser',value='FUCKING LOSER',inline=True)
  gen.add_field(name='Mazyquotes',value='Kinda sussy',inline=True)
  gen.add_field(name='Nukes',value='Death',inline=True)
  gen2 = discord.Embed(color=0xF83252)
  gen2.add_field(name='Oath',value='Worthless bot fucker',inline=True)
  gen2.add_field(name='RacistLiam',value='Biggie racist',inline=True)
  gen2.add_field(name='RoseQuotes',value='sus',inline=True)
  gen2.add_field(name='TheTruth',value="Hurts doesn't it?",inline=True)
  gen2.add_field(name='War',value='Breaking necks since 2020',inline=True)
  gen2.add_field(name='WhoLovesLiam',value='Not found',inline=True)
  gen2.add_field(name='YeeYeeHaircut',value='Dayum',inline=True)
  gen2.add_field(name='batcock',value='Dad',inline=True)
  gen2.add_field(name='batcock_rage',value='reeee',inline=True)
  gen2.add_field(name='batockslovers',value='owa owa',inline=True)
  gen2.add_field(name='caveman',value='Oogabooga',inline=True)
  gen2.add_field(name='creators',value='We are #1',inline=True)
  gen2.add_field(name='degenerate_scum',value='Fucking degenerate',inline=True)
  gen2.add_field(name='freemanquotes',value='Faguito',inline=True)
  gen2.add_field(name='gay',value='It is very true',inline=True)
  gen2.add_field(name='gayassgavin',value='Faguet',inline=True)
  gen2.add_field(name='getpfp',value='Gets your or another members profile picture',inline=True)
  gen2.add_field(name='hack',value='Hacks a member of your choice',inline=True)
  gen2.add_field(name='help',value='Shows this message',inline=True)
  gen2.add_field(name='im14andthisisdeep',value='Sad boi hours',inline=True)
  gen2.add_field(name='info',value='Displays info about a member',inline=True)
  gen2.add_field(name='instantweebdepression',value='The sadness',inline=True)
  gen2.add_field(name='jackquotes',value='Good pounding',inline=True)
  gen2.add_field(name='josiequotes',value='Cringe',inline=True)
  gen3 = discord.Embed(color=0xF83252)
  gen3.add_field(name='littlegirls',value='FBI please just avert your eyes',inline=True)
  gen3.add_field(name='pooper',value='Stank like ur mom',inline=True)
  gen3.add_field(name='rape',value='Rape someone today',inline=True)
  gen3.add_field(name='retard',value='It is true',inline=True)
  gen3.add_field(name='search',value='Searches the interwebs',inline=True)
  gen3.add_field(name='sewerslide',value='Just do it - Shia LaBeouf',inline=True)
  gen3.add_field(name='shutupretard',value='Shut your bitchass up',inline=True)
  gen3.add_field(name='stfu',value='Shut it',inline=True)
  gen3.add_field(name='tractor',value='She likes it',inline=True)
  gen3.add_field(name='wanted',value='Bad boi',inline=True)
  gen3.add_field(name='whereis_Batock',value='Pull up',inline=True)
  gen3.add_field(name='whereis_Blacktrick',value='Pull up',inline=True)
  gen3.add_field(name='whois_2match2',value='Short answer: bitch',inline=True)
  gen3.add_field(name='whois_Adon',value='Legend',inline=True)
  gen3.add_field(name='whois_Agent',value='Smile',inline=True)
  gen3.add_field(name='whois_Alyssa',value='Bitch',inline=True)
  gen3.add_field(name='whois_Amp',value='This kid is cancer, still better than lib tho',inline=True)
  gen3.add_field(name='whois_BT3025',value='Our own Baljeet',inline=True)
  gen3.add_field(name='whois_Batcock',value='Our father',inline=True)
  gen3.add_field(name='whois_Blacktrick',value='Bot daddy',inline=True)
  gen3.add_field(name='whois_Crisp',value='Crispy dood',inline=True)
  gen3.add_field(name='whois_Cum',value='Hot',inline=True)
  gen3.add_field(name='whois_Cutecouple',value='Cutest',inline=True)
  gen3.add_field(name='whois_Dew',value='An absalute legend of a human being',inline=True)
  gen4 = discord.Embed(color=0xF83252)
  gen4.add_field(name='whois_Hoe',value='Hoes',inline=True)
  gen4.add_field(name='whois_Idiot',value='Figure it out from the command',inline=True)
  gen4.add_field(name='whois_Imm',value='Ass',inline=True)
  gen4.add_field(name='whois_Jessica',value='Fag',inline=True)
  gen4.add_field(name='whois_Josie',value='Anime fucker',inline=True)
  gen4.add_field(name='whois_JosieBoyfriend',value='A sexy boi',inline=True)
  gen4.add_field(name='whois_Lemen',value='Your god, daddy, and sugardaddy',inline=True)
  gen4.add_field(name='whois_LemensSimp',value='Stoopid',inline=True)
  gen4.add_field(name='whois_Libtard',value='Fucker',inline=True)
  gen4.add_field(name='whois_Mazy',value='Type me',inline=True)
  gen4.add_field(name='whois_Mh',value='the alt god',inline=True)
  gen4.add_field(name='whois_NoLife',value='Slaves',inline=True)
  gen4.add_field(name='whois_Pain',value='Ouch',inline=True)
  gen4.add_field(name='whois_PizzaWithAids',value='Pretty poggas',inline=True)
  gen4.add_field(name='whois_Rose',value='SIMP',inline=True)
  gen4.add_field(name='whois_Seriously',value='Doer of moms',inline=True)
  gen4.add_field(name='whois_Tboner',value='Kicked lmao',inline=True)
  gen4.add_field(name='whois_Tokyo',value='Banned fag',inline=True)
  gen4.add_field(name='whois_kanekiiiiiii',value='Haha ur gae',inline=True)
  gen4.add_field(name='whois_urdad',value='Redneck fishfucker',inline=True)
  gen4.add_field(name='whois_urmom',value='Ugly as fuck',inline=True)
  gen4.add_field(name='wholoveshim',value='NONE',inline=True)
  gen4.add_field(name='yeetusthatfetus',value='Speedy',inline=True)
  gen4.add_field(name='whois_Drift',value='Hah',inline=True)
  gen5 = discord.Embed(color=0xF83252)
  await ctx.send(embed=gen)
  await ctx.send(embed=gen2)
  await ctx.send(embed=gen3)
  await ctx.send(embed=gen4)